name: BetterCombatLogging
version: '1.0-SNAPSHOT'
main: net.saturn.BetterCombatLogging
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]
softdepend: [ WorldGuard ]

commands:
  combat:
    description: Check your combat status
    usage: /<command>

  protectionlimit:
    description: Manage global protection enchantment limits
    usage: /<command> <set|remove|check> [level]
    permission: BetterCombatLogging.admin

  blockedregion:
    description: Manage regions blocked during combat
    usage: /<command> <add|remove|list|clear> [region]
    permission: BetterCombatLogging.admin
    aliases: [br, blockedregions]

  activatecombat:
    description: Manually activate combat mode for a player (testing)
    usage: /<command> <player>
    permission: BetterCombatLogging.admin
    aliases: [combattest, testcombat]

  setcombatduration:
    description: Set the combat duration in seconds
    usage: /<command> <seconds>
    permission: BetterCombatLogging.admin
    aliases: [combatduration, setcombat]

  cleanup:
    permission: op


permissions:
  BetterCombatLogging.admin:
    description: Allows use of admin commands
    default: op